# Generated by Django 4.2 on 2023-04-23 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_event_booking_csv_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='TestModel',
            name='time_range',
            field=datetimeutc.fields.DateTimeUTCField(),
        ),
    ]
